# Generated by Django 4.2.6 on 2023-10-19 03:25

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusPackages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_big', models.ImageField(upload_to='bus_packages')),
                ('type', models.CharField(blank=True, max_length=200, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('duration', models.CharField(blank=True, max_length=20, null=True)),
                ('second_image', models.ImageField(upload_to='bus_packages')),
                ('third_image', models.ImageField(upload_to='bus_packages')),
                ('fourth_image', models.ImageField(upload_to='bus_packages')),
                ('description', ckeditor.fields.RichTextField()),
                ('off_price', models.IntegerField()),
                ('adult_price', models.IntegerField(verbose_name='Enter the price for Adults (19-99)')),
                ('youth_price', models.IntegerField(verbose_name='Enter the price for Youths (6-18)')),
                ('infant_price', models.IntegerField(verbose_name='Enter the price for Infants (0-5)')),
            ],
        ),
    ]
