# Generated by Django 4.2.6 on 2023-10-19 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_buspackages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buspackages',
            name='adult_price',
            field=models.IntegerField(verbose_name='Enter the price for Adults (19-99) in USD'),
        ),
        migrations.AlterField(
            model_name='buspackages',
            name='infant_price',
            field=models.IntegerField(verbose_name='Enter the price for Infants (0-5) in USD'),
        ),
        migrations.AlterField(
            model_name='buspackages',
            name='off_price',
            field=models.IntegerField(verbose_name='Enter the off price (USD)'),
        ),
        migrations.AlterField(
            model_name='buspackages',
            name='youth_price',
            field=models.IntegerField(verbose_name='Enter the price for Youths (6-18) in USD'),
        ),
    ]
