# Generated by Django 4.2.6 on 2023-10-19 11:25

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_date_museumpackage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MuseumPackages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_big', models.ImageField(upload_to='museum_packages')),
                ('type', models.CharField(blank=True, max_length=200, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('duration', models.CharField(blank=True, max_length=20, null=True)),
                ('second_image', models.ImageField(upload_to='museum_packages')),
                ('third_image', models.ImageField(upload_to='museum_packages')),
                ('fourth_image', models.ImageField(upload_to='museum_packages')),
                ('description', ckeditor.fields.RichTextField()),
                ('off_price', models.IntegerField(verbose_name='Enter the off price (USD)')),
                ('adult_price', models.IntegerField(default=0, verbose_name='Enter the price for Adults (19-99) in USD')),
                ('youth_price', models.IntegerField(verbose_name='Enter the price for Youths (6-18) in USD')),
                ('infant_price', models.IntegerField(verbose_name='Enter the price for Infants (0-5) in USD')),
                ('dates', models.ManyToManyField(to='api.date')),
            ],
        ),
        migrations.DeleteModel(
            name='MuseumPackage',
        ),
    ]
