# Generated by Django 4.2.6 on 2023-10-19 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_museumpackages_adult_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='buspackages',
            name='package_tag',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
