# Generated by Django 4.2.6 on 2023-10-19 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_buspackages_package_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='museumpackages',
            name='package_tag',
            field=models.IntegerField(default=16117),
        ),
        migrations.AlterField(
            model_name='buspackages',
            name='package_tag',
            field=models.IntegerField(default=18944),
        ),
    ]
