# Generated by Django 4.2.6 on 2023-10-25 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_buspackages_package_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buspackages',
            name='package_tag',
            field=models.IntegerField(default=74699),
        ),
        migrations.AlterField(
            model_name='museumpackages',
            name='package_tag',
            field=models.IntegerField(default=36875),
        ),
    ]
