# Generated by Django 4.2.6 on 2023-10-30 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_purchasedtickets_alter_buspackages_package_tag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedtickets',
            name='qr_content',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='buspackages',
            name='package_tag',
            field=models.IntegerField(default=97570),
        ),
        migrations.AlterField(
            model_name='museumpackages',
            name='package_tag',
            field=models.IntegerField(default=73118),
        ),
    ]
