# Generated by Django 4.2.6 on 2023-10-31 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_buspackages_package_tag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buspackages',
            name='purchased_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='museumpackages',
            name='purchased_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='buspackages',
            name='package_tag',
            field=models.IntegerField(default=53542),
        ),
        migrations.AlterField(
            model_name='museumpackages',
            name='package_tag',
            field=models.IntegerField(default=14113),
        ),
    ]
