# Generated by Django 4.2.6 on 2023-10-31 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_buspackages_purchased_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buspackages",
            name="package_tag",
            field=models.IntegerField(default=45189),
        ),
        migrations.AlterField(
            model_name="museumpackages",
            name="package_tag",
            field=models.IntegerField(default=63469),
        ),
    ]
