# Generated by Django 4.2.6 on 2024-02-20 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_alter_buspackages_package_tag_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buspackages",
            name="package_tag",
            field=models.IntegerField(default=48439),
        ),
        migrations.AlterField(
            model_name="museumpackages",
            name="package_tag",
            field=models.IntegerField(default=53640),
        ),
    ]
