# Generated by Django 4.2.6 on 2024-02-20 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_alter_buspackages_package_tag_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchasedtickets",
            name="purchased_date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="buspackages",
            name="package_tag",
            field=models.IntegerField(default=81358),
        ),
        migrations.AlterField(
            model_name="museumpackages",
            name="package_tag",
            field=models.IntegerField(default=26426),
        ),
    ]
