# Generated by Django 4.2.6 on 2024-02-26 15:39

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_purchasedtickets_purchased_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privacy_policy', ckeditor.fields.RichTextField()),
                ('about_us', ckeditor.fields.RichTextField()),
                ('return_policy', ckeditor.fields.RichTextField()),
                ('refund_policy', ckeditor.fields.RichTextField()),
                ('terms_and_conditions', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.AlterField(
            model_name='buspackages',
            name='package_tag',
            field=models.IntegerField(default=64520),
        ),
        migrations.AlterField(
            model_name='museumpackages',
            name='package_tag',
            field=models.IntegerField(default=75488),
        ),
    ]
